name: Docker Registry
version: "1.0"
slug: docker-registry
description: Run a private Docker Registry inside Home Assistant.
startup: services
arch:
  - amd64
  - armv7
  - aarch64
boot: auto
map:
  - config
  - ssl
options: {}
schema: {}
