name: Docker Registry
version: 4.0.8
slug: docker-registry
description: Run a private Docker Registry inside Home Assistant.
startup: application
arch:
  - amd64
  - armv7
  - aarch64
boot: auto
init: false
map:
  - config
  - ssl
  - registry:rw
ports:
  5001/tcp: 5001
options:
  registry_port: 5001
schema:
  registry_port: int
