name: Docker Registry
version: 4.0.5
slug: docker-registry
description: Run a private Docker Registry inside Home Assistant.
startup: services
arch:
  - amd64
  - armv7
  - aarch64
boot: auto
map:
  - config
  - ssl
  - registry:rw
ports:
  5000/tcp: 5000
options:
  registry_port: 5000
schema:
  registry_port: int
