name: Docker Registry
version: 4.0.12
slug: docker-registry
description: Run a private Docker Registry inside Home Assistant.
startup: application
arch:
  - amd64
  - armv7
  - aarch64
boot: auto
init: false
map:
  - config
  - ssl
  - registry:rw
ports:
  5001/tcp: 5001
options:
  registry_port: 5001
  ssl_enabled: false
  username: null
  password: null
schema:
  registry_port: int
  ssl_enabled: bool
  username: str?
  password: str?
